region                        = "us-east-2"
networking_vpc_cidr_block     = "10.0.0.0/16"
networking_subnet_cidr_blocks = ["10.0.1.0/24"]
app_instance_type             = "m5a.xlarge"
app_volume_size               = "200" # in GB
app_volume_type               = "gp2"
app_key_name                  = "MorpheusAccess"
app_os_flavor                 = "ubuntu"
internal_only                 = false